#! /usr/bin/env bash

#PBS -l walltime=08:00:00
#PBS -l nodes=1:ppn=40
#PBS -A PAS0254
#PBS -j oe

cd "$PBS_O_WORKDIR" || exit $?

./compile_all.sh 40 &> compile_all.out

if [ "$?" -eq "0" ]
then
	./driver.sh projectile="Pb" target="Pb" beamEnergy="2760.0" Nevents=100 ThermalOnly='true' SetPartonVertices='off' &>> driver.out
	./driver.sh projectile="Pb" target="Pb" beamEnergy="2760.0" Nevents=100 ThermalOnly='false' SetPartonVertices='off' &>> driver.out
fi
